#!/bin/bash

# run_instance.sh — run the measured operation and report the verdict.
# Arguments (the interface version, then the instance's instances.csv columns in file order):
# - $1: interface version string, e.g. "v1"
# - $2: benchmark,  the set representation, e.g. "zonotope" or "zonotope-batched"
# - $3: instance,   "<operation>-<n>d[-b<batch>]-<device>", e.g. "matMul-500d-b10-gpu"
# - $4: repetition, how often to repeat the operation within this run, e.g. "100"
# - $5: device,     "cpu" or "gpu"
# - $6: params,     JSON object with the operation's arguments, e.g.
#                   '{"dim": 500, "device": "gpu", "batch_size": 10}'
# A column added to the catalog later arrives as a further argument, in file order, and
# the results file to write is always the LAST argument.
#
# Everything this script does is timed, so it must do nothing but the operation: the
# inputs were already generated by prepare_instance.sh. Read them back once, then perform
# the operation $REPETITION times, so that one measurement averages over repeats rather
# than timing a single noisy call.
#
# The harness owns timing: it measures the wall-clock time of this script and enforces
# the per-instance timeout (the "timeout" column in instances.csv, if the catalog sets
# one; otherwise the run is uncapped). Do not sleep to a deadline yourself.

set -e

VERSION_STRING="v1"
if [ "$1" != "$VERSION_STRING" ]; then
    echo "Expected first argument (version string) '$VERSION_STRING', got '$1'"
    exit 1
fi

BENCHMARK="$2"
INSTANCE="$3"
REPETITION="$4"
DEVICE="$5"
PARAMS="$6"
# The results file is always the last argument.
RESULTS_FILE="${@: -1}"

# The instance name carries the operation; its arguments come from the params JSON.
# python3 is always present on the worker (the harness itself runs on it).
# batch_size is absent on the unbatched benchmarks, hence the default of 1.
OPERATION="${INSTANCE%%-*}"
read -r DIM BATCH_SIZE <<EOF
$(printf '%s' "$PARAMS" | python3 -c 'import json,sys; p=json.load(sys.stdin); print(p["dim"], p.get("batch_size", 1))')
EOF

# Same path prepare_instance.sh wrote to; both run with the tool directory as their cwd.
INPUT_FILE="inputs/${BENCHMARK}-${INSTANCE}.input"

echo "Running $OPERATION on $BENCHMARK in ${DIM}d, batch $BATCH_SIZE, x$REPETITION, on $DEVICE -> $RESULTS_FILE"

# Report unsupported rather than silently falling back to the CPU, which would otherwise
# be recorded as a GPU measurement.
# TODO: drop this once your library runs on the GPU.
if [ "$DEVICE" = gpu ]; then
    echo "No GPU support; reporting unsupported."
    printf 'result\nunsupported\n' > "$RESULTS_FILE"
    exit 0
fi

# TODO: call your library here, and nothing else — this is the measured region. Pass it
# $OPERATION, $BENCHMARK, $DIM, $BATCH_SIZE, $DEVICE, $REPETITION and "$INPUT_FILE", and
# let it dispatch on the operation itself: read the prepared inputs once, then perform the
# operation $REPETITION times.
# The 1 s stand-in below keeps the skeleton runnable as a test tool until you do; delete it.
sleep 1

# One of: finished (the operation ran), unsupported (your library cannot run this
# instance), error (the run failed). Timing is the harness's business, not a verdict.
VERDICT="finished"

# Write the results file: a header row plus one data row with a "result" column. Any
# further columns you add are kept per instance alongside the verdict, so a library can
# report its own breakdown next to the harness wall-clock:
#   printf 'result,time_read,time_operation\n' > "$RESULTS_FILE"
#   printf '%s,%s,%s\n' "$VERDICT" "$t_read" "$t_op" >> "$RESULTS_FILE"
printf 'result\n%s\n' "$VERDICT" > "$RESULTS_FILE"
